name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK 14
        uses: actions/setup-java@v1.4.0
        with:
          java-version: 1.14
          java-package: jdk
          architecture: x86

      - name: Build with gradlew
        run: ./gradlew jar --info

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build/libs/*.jar
          if-no-files-found: error
